### ISSUE TITLE
Timestamp decoding

### ISSUE THREAD

**Issue by dselivanov** [wlgq2/uvnsq#1]
It seems there is some bug when decoding timestamps. I'm getting nanoseconds close to 2**64( I've just added `message.Timestamp()` print to the example):
```
18446744073709534504
18446744073126297668
```

**Comment by wlgq2** [comment]
i see……thinks

**Comment by wlgq2** [comment]
i fix this bug，it's because of “  num |=  data[i];”，data[i]'s type is char，maybe a plural。
