### ISSUE TITLE
Error when compiling with uv-cpp 1.4.5

### ISSUE THREAD

**Issue by dselivanov** [wlgq2/uvnsq#2]
Trying to compile latest version.

I'm getting:
> uvnsq/NsqLookupd.cpp:64:21: error: non-const lvalue reference to type 'uv::SocketAddr' cannot bind to a temporary of type 'uv::SocketAddr'
        client->Req((uv::SocketAddr)addr, req);

Seems related to [HttpClient.cpp#L41](https://github.com/wlgq2/uv-cpp/blob/95ad0844ddc2ea47e25a38101e83aedbdb72e813/uv/http/HttpClient.cpp#L41).

Changing signature to `Req(uv::SocketAddr addr, Request& req)` solves the problem.

Would be nice to add to the README.md a version number of uv-cpp which works with uvnsq.

**Comment by wlgq2** [comment]
thank for your feedback。
it's my mistake.
i will make sure uvnsq supports the last version of uv-cpp.
it‘s because i compiled successfully with visual studio，but did not check the compilation of gcc。
I fixed this problem

**Comment by dselivanov** [comment]
Thanks for the quick fix. I can confirm problem resolved.
