### ISSUE TITLE
uvnsq API

### ISSUE THREAD

**Issue by dselivanov** [wlgq2/uvnsq#3]
First of all many thanks for you work!

I've been trying to hack around `uvnsq` and would like to share some feedback.

First of all `NsqConsumer` API might need some restructuring as according to [nsq docs](https://nsq.io/clients/building_client_libraries.html):

> A consumer subscribes to a topic on a channel over a TCP connection to nsqd instance(s). You can only subscribe to one topic per connection so multiple topic consumption needs to be structured accordingly.

Real life usage is similar - one NSQ topic, but many nsqd connections. So I'm wondering if `appendSub` method can add new nsqd connection rather than topic ?

**Comment by wlgq2** [comment]
yes，one connection can only subscribe to one topic && channel.

**Comment by wlgq2** [comment]
do you mean a NsqConsumer object append multiple tcp connection？
i think this is unreasonable. one consumer should subscribe one topic。you can new multiple consumers object to manage multiple topics。
this consumers can run on the same loop(thread).  so you can share variables to pass data.

**Comment by dselivanov** [comment]
Yes, I mean 1 consumer = 1 nsq topic and multiple connections to multiple nsqd.

**Comment by wlgq2** [comment]
do you mean one consumer  connect to multiple nsqd?

**Comment by wlgq2** [comment]
I will consider how to implement this feature.

**Comment by dselivanov** [comment]
I've tried to build such functionality myself using multiple `NsqConsumer` objects. But I'm still not sure how to properly close nsqd connections. Is it just by deleting `NsqConsumer` instance? Do I need somehow to "de-register" such consumer from event loop? 

Sorry for these questions, I'm not an expert in  `llibuv`...

**Comment by wlgq2** [comment]
1.i delete appendSub  and Added appendNsqd interface for multiple nsqd.
2. deleting NsqConsumer  object will disconnect all connection.but, it's not thread-safe,you can only delete NsqConsumer  object in the loop thread.
3.you need to update uv-cpp to version 1.4.8

**Comment by dselivanov** [comment]
@wlgq2 thank you very much for implementing this feature! 

Couple of more questions:
- what if I need to close only a particular nsqd connection? This is a valid case where consumer polling nsqdlookup and watch for new and stale connections (which it needs to add and and remove). So may be it worth to add `removeNsqd` method?
- "only delete NsqConsumer object in the loop thread" - you mean where loop is running, right?
- is appending nsqd thread safe?

**Comment by wlgq2** [comment]
@dselivanov 
1.  not support close  a particular nsqd connection. uvnsq will auto reconnect a nsqd  when this nsqd disconnected.
2. i mean，delete NsqConsumer must called in libuv‘s event loop。because libuv is not thread safe. you can use uv::EvnetLoop::runInThisLoop to register a callback run in libuv’s loop。all uvnsq callback run in libuv‘s loop(this means called from uv::EventLoop::run function)。
3. i recommend appending nsqd before loop->run();

**Comment by dselivanov** [comment]
Thanks for the answers. The challenge for 1 and 3 is that nsqd producer can come and go. 

For example I want to run consumer and read from `topic_1`. 
1. I call `nsqlookupd` and ask what are `nsqd` which have `topic_1`. Suppose these nsqd are `nsqd_1` and `nsqd_2`. 
1. Then I connect to `nsqd_1` and `nsqd_2` and start handle messages
1. Time to time I poll `nsqlookupd` to check what are the `nsqd` which have `topic_1`. And for example at some point of time `nsqlookupd` says that there is new `nsqd_3` which also has `topic_1`. Then I need to append  `nsqd_3` and add it to the event loop.
1. It is very good that `NsqConsumer` will try to reconnect to `nsqd` automatically. But there is possibility that some `nsqd` can completely finish, so it makes sense to remove such connections  from consumer. So it would be nice to have a method to remove `nsqd` by host and port: `void removeNsqd(string host, uint16_t port)`

**Comment by wlgq2** [comment]
this will make the code complicated，if support for dynamically adding and deleting nsq nodes.

**Comment by dselivanov** [comment]
yeah, I know, but this is the whole purpose of the `nsqlookupd` within NSQ architecture. And this is the most popular pattern of NSQ usage...

**Comment by dselivanov** [comment]
I've been playing with the latest `uvnsq` and it seems there several parts which are necessary for dynamic nsqd:

1. in `NsqConsumer` each connection to nsqd shoud have some id (for example string `host:port`)
1. Need somehow to track from which connection message came from in order to call `fin` method to the right nsqd.

**Comment by wlgq2** [comment]
fin auto called in NsqConsumer now .

i will consider whether to support dynamic connect for nsqd, if I have time.

**Comment by wlgq2** [comment]
@dselivanov  
i think the correct design is，one NsqConsumer- one nsqd service. you can use multiple consumers connect multiple nsqds. delete and new consumer for dynamic nsqd.

If you want to deal with multiple nsqd of the same topic，you can set the same callback function for multiple customers while have same topic.

**Comment by dselivanov** [comment]
Thanks, this makes sense. So such design is more similar to what was in previous version (one connection per nsqConsumer and explicit `fin`)

**Comment by wlgq2** [comment]
i update this
